line-length = 80

[lint]

extend-select = [
    "N"
]
extend-ignore = [
    "E402",  # Module level import not at top of file
]


[lint.pep8-naming]
extend-ignore-names = [
    "test_*"
]

[format]

quote-style = "single"
